clone_depth: 1

init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
    matrix:
        - MINGW_VERSION: mingw64
          ARCH: x86_64
          ARCH_BIT: 64
          BUILD_NO: $(appveyor_build_number)

#        - MINGW_VERSION: mingw32
#          ARCH: i686
#          ARCH_BIT: 32
          
matrix:
    fast_finish: true

install:
    # Install Inno Setup
    - choco install InnoSetup

build_script:
    - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
    - C:\msys64\usr\bin\bash build.sh

    - echo "### Push artifacts ... "
    - appveyor PushArtifact c:\scopy-%ARCH_BIT%bit.zip
    - appveyor PushArtifact C:\debug-%ARCH_BIT%bit.zip
   
    # Build the installer
    - appveyor PushArtifact C:\scopy-%ARCH_BIT%-setup.exe
on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
